FROM python:3.12.4

COPY ./requirements.txt /requirements.txt
COPY ./careconnect /careconnect

WORKDIR /careconnect

RUN python -m venv /py && \
    /py/bin/pip install -r /requirements.txt && \
    adduser --disabled-password --no-create-home django-user

ENV PATH="/py/bin:$PATH"

USER django-user

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]